# Generated by Django 4.0.6 on 2022-09-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habits',
            options={'verbose_name': 'ПРИВЫЧКA', 'verbose_name_plural': 'ПРИВЫЧКИ'},
        ),
    ]
